services:
  app:
    container_name: event-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - postgres
    ports:
      - '8082:8082'
  postgres:
    container_name: event-db
    image: 'postgres:17.2'
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
  redis:
    container_name: event-redis
    image: 'redis:7.4'
    ports:
      - '6379:6379'

volumes:
  postgres_data: